# Generated by Django 4.2 on 2025-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0003_rename_assignment_projectassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('voeux', 'Voeux')], default='voeux', max_length=50, unique=True)),
                ('limite_date', models.DateField()),
            ],
        ),
    ]
