# Generated by Django 4.2 on 2025-04-22 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0004_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ges_project_app.project')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ges_project_app.team')),
                ('desired_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_changes', to='ges_project_app.project')),
                ('desired_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_changes', to='ges_project_app.team')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='ges_project_app.student')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectsconflits',
            name='conflit',
        ),
        migrations.RemoveField(
            model_name='projectsconflits',
            name='project',
        ),
        migrations.RemoveField(
            model_name='updateassignment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='updateassignment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Conflit',
        ),
        migrations.DeleteModel(
            name='ProjectsConflits',
        ),
        migrations.DeleteModel(
            name='UpdateAssignment',
        ),
    ]
