# Generated by Django 4.2 on 2025-02-28 10:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voeux',
            options={'ordering': ['student', 'rank']},
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.CharField(choices=[('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='null', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], default='null', max_length=5),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ges_project_app.project'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ges_project_app.student'),
        ),
        migrations.AlterField(
            model_name='conflit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits', to='ges_project_app.project'),
        ),
        migrations.AlterField(
            model_name='conflit',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='conflit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits', to='ges_project_app.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_groups',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsteams',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ges_project_app.student'),
        ),
        migrations.AlterField(
            model_name='studentsteams',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ges_project_app.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_students',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='min_students',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ges_project_app.project'),
        ),
        migrations.AlterField(
            model_name='updateassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ges_project_app.project'),
        ),
        migrations.AlterField(
            model_name='updateassignment',
            name='statut',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='updateassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ges_project_app.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('supervisor', 'Encadrant'), ('admin', 'Administrateur')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='voeux',
            name='note_preference',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='voeux',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to='ges_project_app.project'),
        ),
        migrations.AlterField(
            model_name='voeux',
            name='rank',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='voeux',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voeux', to='ges_project_app.student'),
        ),
        migrations.AlterUniqueTogether(
            name='voeux',
            unique_together={('student', 'project')},
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
