# Generated by Django 4.2 on 2025-03-24 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ges_project_app', '0002_alter_voeux_options_project_level_student_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='ProjectAssignment',
        ),
        migrations.RenameField(
            model_name='projectassignment',
            old_name='statut',
            new_name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectassignment',
            unique_together={('student', 'project')},
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['student'], name='ges_project_student_f02e43_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['project'], name='ges_project_project_b57914_idx'),
        ),
    ]
